print ("hello!!")
name = input("what is your name? ")
print(f"thank you very much {name} this will be very helpful later lets get started")
adjective = input("give me an adjective? ")
nationality= input("give me an nationality? ")
person= input("give me an person? ")
noun= input("give me an noun? ")
adjective2= input("give me an color? ")
noun2= input("give me an noun? ")
adjective3= input("give me an adjective? ")
adjective4= input("give me an texture? ")
plural_noun= input("give me an plural noun? ")
noun3= input("give me an noun? ")
number= input("give me an number? ")
shapes= input("give me some shapes? ")
food= input("give me an food? ")
food2= input("give me an food? ")
number2= input("give me an number? ")
print("*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*")
print(f"pizza was invented by a {adjective} {nationality} ")
print(f"cheif named {person}. to make pizza you need ")
print(f"to make a lump of {noun},and make a thin round ")
print(f"{adjective2} {noun2}. Then you cove it with ")
print(f"{adjective3} sauce,{adjective4} cheese and fresh ")
print(f"chopped,{plural_noun}. Next you have to bake it in a very ")
print(f"hot {noun3}, when it is done cut it into {number} ")
print(f"{shapes} Some kids like {food} pizza the")
print(f"best, but my favorite is the {food2} pizza. If I could, I ")
print(f"would eat pizza {number2} a day ")
print("*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*ʕ•ᴥ•ʔ*")